# Custom Language File for Launcher Customizer

[ejs.app]
title = "Wenjah Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Azurz/WenjahLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://youtube.com/wenjah"
mediaDiscordURL = "https://discord.gg/BSf68PPPKt"

[ejs.settings]
sourceGithubLink = "https://github.com/Azurz/WenjahLauncher"
supportLink = "https://github.com/Azurz/WenjahLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENU"
welcomeDescription = "#"
welcomeDescCTA = "#"
